/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { createFileRoute } from '@tanstack/react-router'

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as SimulationImport } from './routes/simulation'
import { Route as OptimizationImport } from './routes/optimization'

// Create Virtual Routes

const IndexLazyImport = createFileRoute('/')()

// Create/Update Routes

const SimulationRoute = SimulationImport.update({
  id: '/simulation',
  path: '/simulation',
  getParentRoute: () => rootRoute,
} as any)

const OptimizationRoute = OptimizationImport.update({
  id: '/optimization',
  path: '/optimization',
  getParentRoute: () => rootRoute,
} as any)

const IndexLazyRoute = IndexLazyImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/index.lazy').then((d) => d.Route))

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexLazyImport
      parentRoute: typeof rootRoute
    }
    '/optimization': {
      id: '/optimization'
      path: '/optimization'
      fullPath: '/optimization'
      preLoaderRoute: typeof OptimizationImport
      parentRoute: typeof rootRoute
    }
    '/simulation': {
      id: '/simulation'
      path: '/simulation'
      fullPath: '/simulation'
      preLoaderRoute: typeof SimulationImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export interface FileRoutesByFullPath {
  '/': typeof IndexLazyRoute
  '/optimization': typeof OptimizationRoute
  '/simulation': typeof SimulationRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexLazyRoute
  '/optimization': typeof OptimizationRoute
  '/simulation': typeof SimulationRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexLazyRoute
  '/optimization': typeof OptimizationRoute
  '/simulation': typeof SimulationRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/optimization' | '/simulation'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/optimization' | '/simulation'
  id: '__root__' | '/' | '/optimization' | '/simulation'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexLazyRoute: typeof IndexLazyRoute
  OptimizationRoute: typeof OptimizationRoute
  SimulationRoute: typeof SimulationRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexLazyRoute: IndexLazyRoute,
  OptimizationRoute: OptimizationRoute,
  SimulationRoute: SimulationRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/optimization",
        "/simulation"
      ]
    },
    "/": {
      "filePath": "index.lazy.tsx"
    },
    "/optimization": {
      "filePath": "optimization.tsx"
    },
    "/simulation": {
      "filePath": "simulation.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
